// Full complaint / petition / RTI text for each dashboard record (public, redacted copy).
// Loaded on demand by the "Show full complaint text" expand buttons in index.html.
// Note: record 16 (Grievance #19075234) is intentionally omitted from this file.
window.PETITION_TEXTS = {
  "1": "There is an open drainage/sewage leak on Poolakshmi Street, Soosaiya Nagar, Noombal, within Thiruverkadu Municipality limits, where contaminated waste water is continuously leaking onto the public road and stagnating in pools mixed with debris and broken pavement stones. This is a serious public health hazard - breeding mosquitoes, spreading foul odour, and posing a real risk of waterborne disease to residents, especially children and the elderly who use this road daily. The road surface itself is being eroded by the constant water flow.\n\nUnder Section 61 of the Tamil Nadu District Municipalities Act, 1920, all public drains and sewers within municipal limits vest in the Municipal Council, and under Section 61A, the Council is duty-bound to maintain and repair them. Allowing this leak to persist is a direct dereliction of that statutory duty. Continued neglect also amounts to a public nuisance under Sections 270, 279 and 280 of the Bharatiya Nyaya Sanhita, 2023 - fouling public water and rendering the atmosphere noxious to public health.\n\nWe demand immediate inspection and permanent repair of the drainage line, with written confirmation of the corrective action taken and a firm timeline. Failure to act will leave residents no option but to escalate this matter through the Right to Information Act and to the Tamil Nadu Local Bodies Ombudsman for administrative negligence.\n\n--- OFFICER'S REASON FOR ACCEPTANCE (translated from Tamil, 19-Sep-2026) ---\nThe petitioner's request has been carefully examined. To install storm-water drain covers where covers are damaged/unsafe or missing, two works - Ward No.1 to 9, and Ward No.10 to 18 - worth Rs.24.50 lakh have gone to tender as of 29.09.2026. Once the tenders are received, work orders will be issued and action taken to complete the work quickly.",

  "2": "Water pollution complaint filed with TNPCB regarding sewage discharge continuously stagnating on the public road at Poolakshmi Street, Soosaiya Nagar, Noombal, within Thiruverkadu Municipality limits - the same underlying leak reported to CM Helpline as Grievance #18764409. TNPCB's online portal only accepts PDF/document uploads, not photos or video, so the supporting photo/video evidence filed with the CM Helpline grievance was not attached here; the complaint text cross-references Grievance #18764409 for that evidence.",

  "3": "Draft complaint to the Tamil Nadu Local Bodies Ombudsman alleging maladministration by Thiruverkadu Municipality over the same Poolakshmi Street sewer leak (Grievance #18764409) and the water pollution it has caused (TNPCB Complaint 142656429) - cross-citing both as evidence of a civic body failing its statutory duty. This complaint was drafted and addressed to the Ombudsman, Commissioner Thiruverkadu Municipality, and Collector Thiruvallur District, but as of the last check was not confirmed as actually sent (status: Drafted).",

  "4": "ORIGINAL PETITION (filed pre-existing, before this ledger began):\nRoad-laying was requested in the earlier petition to CM Cell for this area, which was last laid at least 5 years back. The petitioner was told it would be discussed in the 2025 budget and given first priority, but nothing has happened. The road is in complete disrepair and cannot even be cycled at 10 km/h. The local councillor was also contacted but this ended in vain. Action was requested against the erring official for the inaction, along with an audit of the Kattupakkam panchayat finances. The request was for a proper road and street lights as a basic need, for the safety of women and senior citizens.\n\n--- OFFICER'S REASON FOR ACCEPTANCE (translated from Tamil) ---\nFollowing the petition received for street lighting and road facilities in Kattupakkam Panchayat, Poovirundhavalli Panchayat Union: street lights have now been installed by the Panchayat administration, and the road work has been entered at Page No.48, Entry No.41 in the register maintained by the Panchayat Union. It is stated that action will be taken to take up the work on a priority basis using Panchayat general funds or some other scheme.\n\n--- #APPEAL FILED 15-SEP-2026 ---\nThis grievance was marked Accepted only on the basis that the road work has been logged in the Panchayat Union register (file no.48/entry no.41), with no sanctioned budget, no funding source confirmed, and no completion timeline - only a statement that action \"will be taken\" through general funds or some other scheme. Streetlights were installed, but the road itself, the primary and original request, remains unlaid more than 5 years after it was first damaged. A related escalation, Grievance #18769965, received a verbal call on 28-Aug-2026 stating measurements were taken on-site, but no survey report or work order has been shared and no construction has started since. We request: (1) a written work order/sanction letter with the funding source and a firm completion date for the road, (2) a copy or confirmation of the measurement/survey referred to in the 28-Aug call under #18769965, and (3) an explanation for the delay since this was first raised over 5 years ago.",

  "5": "Condition of the road for the past 3 years, no improvement, unclear where the fund goes and is utilized.\n\nThe road at Sri Devi Nagar, Kattupakkam has never been properly laid/tarred in over 5 years and is currently in a state of complete disrepair - potholed, uneven, and hazardous for residents, vehicles, and children walking to school. This poses a serious risk of accidents, especially during rains when the road turns into a muddy, waterlogged stretch.\n\nDespite an earlier grievance (Reference #17638563) already raised on this exact issue, no remedial action has been taken to date. This continued inaction is a direct dereliction of the Village Panchayat's statutory duty under Section 110 of the Tamil Nadu Panchayats Act, 1994, which mandates the Panchayat to make reasonable provision for the construction, repair, and maintenance of all village roads within its limits.\n\nDespite repeated representations made to the local Ward Councillor/Panchayat President over these years, no visible action has been taken to get this road surveyed, sanctioned, or laid. This raises serious questions about the elected representative's accountability to residents on a matter as basic as civic road infrastructure, and we expect the Councillor's role and follow-up (or lack thereof) on this issue to be recorded as part of this complaint's review.\n\nThis is not a new problem - it has persisted for over five years without resolution, reflecting sustained administrative neglect. We demand that the road be surveyed, properly laid/tarred, and completed within a fixed and reasonable timeline, with written confirmation of the works undertaken. Continued failure to act will compel residents to escalate this matter to the Tamil Nadu Local Bodies Ombudsman for maladministration, and pursue further redressal through the Right to Information Act.",

  "6": "Attached are the atrocities of the dogs and pigs.\n\nResidents of 1st Street and 2nd Street, Moogambigai Nagar, under Thiruverkadu Municipality, have faced over a year of unchecked stray dog and pig menace, with dogs chasing vehicles and pigs obstructing roadways, resulting in near-accidents and public chaos. This constitutes a public nuisance endangering the safety and convenience of residents and commuters, actionable under Sections 270, 279 and 280 of the Bharatiya Nyaya Sanhita 2023. As the streets in question vest in and are the responsibility of the Municipal Council under Section 61 of the Tamil Nadu District Municipalities Act 1920, the Municipality is duty-bound to ensure they remain safe for public use. We request the Commissioner, Thiruverkadu Municipality, to initiate a time-bound stray animal control and rehoming programme in the affected streets within 30 days and to provide a written status update to residents on the action taken.",

  "7": "The roads at Judges Colony Link Road and 2nd Road, under Thiruverkadu Municipality, have remained in a severely damaged condition for over a year, causing continuous hardship and safety risk to residents. Despite the passage of significant time, no Municipal Engineer has visited the site to assess or initiate repair works. Under the Tamil Nadu District Municipalities Act 1920, Section 61, these streets vest in the Municipal Council, and Section 162 casts a clear statutory duty on the Council to maintain and repair such streets. The continued neglect also raises public safety concerns actionable under Sections 270, 279 and 280 of the Bharatiya Nyaya Sanhita 2023. We request the Commissioner, Thiruverkadu Municipality, to depute Engineering staff for immediate inspection and to undertake time-bound restoration of both roads within 30 days of this petition.",

  "8": "Garbage has been left uncleared for over two weeks on Poolakshmi Street and MSG Road, Susai Nagar, Thiruverkadu, causing foul odour and health hazards to residents. This is a public nuisance under Sections 270 and 279 of the Bharatiya Nyaya Sanhita 2023, and street cleanliness/waste management within municipal limits is a statutory duty of the Municipal Council under Section 162 of the Tamil Nadu District Municipalities Act 1920. We request the Commissioner, Thiruverkadu Municipality, to arrange immediate clearance and regular collection within 7 days of this petition.",

  "9": "Solid waste has been left uncollected for weeks at Sri Devi Nagar, Kattupakkam Village Panchayat, causing unhygienic conditions and health hazards to residents. This is a public nuisance under Sections 270 and 279 of the Bharatiya Nyaya Sanhita 2023, and waste management within the panchayat is a statutory duty under the Tamil Nadu Panchayats Act 1994. We request the Block Development Officer to arrange immediate clearance and regular collection within 7 days of this petition.",

  "10": "Sent by email (no live copy on file for this entry - no CM Helpline ticket exists for it). Raised the same core issue later filed formally at CM Helpline as Grievance #19075234: Thiruverkadu Municipality's proposal to construct a Sewage Pumping Station inside Judges Colony Park (OSR land), objecting to loss of a resident-maintained children's park and the lack of prior consultation.",

  "11": "There are no street name boards installed on the interior roads within Judges Colony, Noombal, Thiruverkadu Municipality. This absence causes daily hardship to residents and visitors in identifying addresses, and hampers postal and emergency services from locating homes accurately. Under Section 61 of the Tamil Nadu District Municipalities Act 1920, all streets within the Municipality vest in and are the responsibility of the Municipal Council, and Section 162 of the same Act casts a duty on the Council to properly maintain such streets, which includes essential signage for identification. The Ward Councillor and Municipal authorities have not acted on this long-standing civic deficiency despite it being a basic requirement for residents. We request the Commissioner, Thiruverkadu Municipality, to arrange for the installation of name boards on all streets in Judges Colony within a reasonable, time-bound period and to confirm the completion of this work to residents.",

  "12": "Residents of Judges Colony, Thiruverkadu Municipality, particularly houses located downhill after Justice Square Apartment, have suffered flooding of their homes during rains for over five years due to incomplete and improperly planned storm water drainage work. The current drainage layout has connected relatively less-affected households while bypassing the most severely affected residences, raising concerns over the technical rationale applied in the design. Under Section 61 of the Tamil Nadu District Municipalities Act 1920, storm water drains vest in and are the responsibility of the Municipal Council, and Section 162 casts a statutory duty on the Municipality to construct and maintain such infrastructure adequately. The continued waterlogging also poses a public health and safety hazard actionable under Sections 270, 279 and 280 of the Bharatiya Nyaya Sanhita 2023. We request the Commissioner, Thiruverkadu Municipality, to conduct a technical review of the drainage alignment, ensure the worst-affected households are covered in the corrective works, and complete the extension/rectification of the storm water drain within a fixed, reasonable timeframe.",

  "13": "Full text not retrievable - this grievance ID (#18932861) does not appear anywhere in the filing account's own CM Helpline ticket list, and its ticket link returns \"Insufficient Privileges.\" Unconfirmed whether this was actually filed under this login, the ID was recorded incorrectly at the time, or it never went through.",

  "14": "The stretch of Oil Mill Road (A N Ezhumalai Salai) in Iyyapanthangal Panchayat was dug up over six months ago for Metro Water pipeline installation, and the road surface has not been restored since. This has narrowed the usable carriageway, causing severe inconvenience and safety hazards to residents, pedestrians, and vehicular traffic in the area. Under Section 110 of the Tamil Nadu Panchayats Act 1994, the Village Panchayat is duty-bound to construct, repair, and maintain village roads within its jurisdiction. The prolonged, unrepaired excavation also constitutes a public nuisance and safety obstruction under Sections 270 and 280 of the Bharatiya Nyaya Sanhita 2023. Despite the extended duration of this hazard, no corrective action has been taken by the Iyyapanthangal Panchayat officials responsible for road maintenance. We request that the Panchayat authority direct immediate restoration of the road surface and complete repair works within 30 days, and that accountability be fixed for the officials whose inaction has allowed this hazard to persist.",

  "15": "Water wastage and sanitary nuisance.\n\nResidents on Perumal Koil Street, Noombal, Thiruverkadu Municipality, have been affected for the past one week by continuous leakage from a metro/water pipeline on the street, causing water stagnation and street damage, compounded by the unexplained removal of the public garbage bin from the locality, leading to accumulation of waste and unsanitary conditions. Supporting photographic and video evidence has been collected and is available for verification. Under Section 61 of the Tamil Nadu District Municipalities Act, 1920, the street and its associated drains vest in and are the responsibility of the Municipal Council, and Section 162 casts a statutory duty on the Council to maintain and repair such streets; the continued leakage and uncollected waste also constitute a public nuisance endangering health and safety under Sections 270, 279 and 280 of the Bharatiya Nyaya Sanhita, 2023. The Ward Councillor has not acted despite the visible and prolonged nature of the problem. We request the Commissioner, Thiruverkadu Municipality, to direct immediate repair of the leaking pipeline and restoration of the garbage bin/regular waste collection at this location within seven working days, and to confirm the corrective action taken to the residents.",

  "17": "No formal petition was filed - resolved via direct resident-to-resident escalation. A resident of Soosaiya Nagar reported a drainage leak near a private business directly to the premises staff and to a neighbour, who called the premises and had the leak cleared the same morning. No CM Helpline grievance or other portal filing was needed for this one.",

  "18": "RTI application filed with the Block Development Office (Panchayat), Poonamallee, seeking: the register entry recorded against Grievance #17638563 (page/entry number, date logged), confirmation of budget/fund sanction status and source for the Sri Devi Nagar road work, the site measurement/survey details referenced in the 28-Aug-2026 phone call under Grievance #18769965 (report or written confirmation), and an explanation for the delay in laying this road since it was first raised over 5 years ago. Registration No. QZRGG/R/2026/60005, fee Rs 10 paid via UPI. Reply due within 30 days (by approx. 15-Oct-2026).",

  "19": "RTI application filed with the Block Development Office (Panchayat), Poonamallee, seeking two sets of information: (A) Kattupakkam Village Panchayat's 5-year audited financial statements, ward-wise scheme works, MGNREGA muster rolls, utilization certificates, and asset details; and (B) the complete garbage collection contract - contractor details, ward-wise vehicle allocation, EV/Swachh Bharat scheme vehicle counts received, worker attendance records, materials issued, wages paid, and any penalty history - filed because garbage collection on the ground is happening only once every 2 days instead of daily. Registration No. QZRGG/R/2026/60006, fee Rs 10 paid via UPI. Reply due within 30 days (by approx. 15-Oct-2026).",

  "20": "The road at Masilamani Street, Andal Nagar, near Velammal School, Vanagaram (adjoining Maharishi Teachers Colony 4th Street), has a large collapsed/sunken patch with loose gravel and debris scattered across the carriageway. This creates a serious risk of accidents for two-wheelers, pedestrians, and school children commuting to Velammal School, especially during night hours and rain when the depression is not clearly visible.\n\nThis stretch requires immediate re-laying/patch repair with proper compaction, not a temporary gravel fill, to prevent recurrence. As this falls within Greater Chennai Corporation limits, we request the Executive Engineer/Zonal Office concerned to inspect the site and carry out permanent repair on priority, given the safety risk to school-going children and daily commuters in this residential area.\n\n--- OFFICER'S REASON FOR ACCEPTANCE ---\n\"Road Cut Work after Tender will be done\"",

  "21": "Respected Sir/Madam, wish to lodge a formal complaint regarding repeated and prolonged power cuts / interruption of power supply affecting Sri Devi Nagar, Kattuppakkam. This has already been raised through the TANGEDCO 1912 helpline but the issue remains unresolved. This is a recurring problem affecting the whole locality. TANGEDCO is requested to inspect the local distribution line/transformer serving Sri Devi Nagar, Kattuppakkam and take corrective action, and to pay compensation as applicable under TNERC standards of performance regulations for the delay already caused."
};
